### ISSUE TITLE
Input question

### ISSUE THREAD

**Issue by zskey-zn** [codeatcg/VRPG#1]
can I use graph-genome ( *.vg or *.gfa file) by VG to visualize ?

**Comment by codeatcg** [comment]
VRPG can cope with pangenome graph in rGFA and GFA formats. We mainly test the program on graph created by Minigraph, Minigraph-CACTUS and PGGB. But for variation graph in GFA format created by VG only a small number of tests were run.  Graph created by vg by using reference genome and variants only include the reference path. The segments from non-reference (variants in VCF file) would be named as 'Un + delimiter + H + delimiter + number' (e.g. Un#H#123) by VRPG-gfa2view.  This is because the information about the origination of the non-reference segments was not saved in the graph created by vg. There is only two colors in a drawing. From the drawing we can't obtain information about the presence/absence   of a segment in the population.

**Comment by zskey-zn** [comment]
Thanks to reply; I use Minigraph-CACTUS to generate graph-genome, then use VRPG to visualization, I  encountered two other issues。

1. when I run gfa2view , report errors ( Segmentation fault )，but result can be visualized with html format , it work  correctly ?
![image](https://github.com/codeatcg/VRPG/assets/55039417/cbe0a900-5aab-4b04-87e2-6ab6db79c500)
![O3I%MUP }{5)UIBG98@W0LV](https://github.com/codeatcg/VRPG/assets/55039417/0e06cd89-2a1b-418e-a41a-b28e17464121)

2. How to display two or more pangenomes ?

**Comment by codeatcg** [comment]
Thanks for using VRPG and feedback issues.
1. Assembly path may be not indexed correctly. The graph can be visualized but the assembly may be not highlighted.  Were '*.path.bdx' and '*.path.bw' files (binary files) in directory 'upload/path' created correctly (file size is not close to zero)? '*.path' are plain text files and you can check whether the sample name and assembly path are abnormal.
2. The function that serves several pangenomes was removed from source code, considering that users may name the pangenomes not properly and the files related to a particular pangenome can't be opened. We'll consider adding this back in next version.

**Comment by zskey-zn** [comment]
Thanks to reply; 
I only have path files，not have index file；
![image](https://github.com/codeatcg/VRPG/assets/55039417/e05ada59-2bf4-43a6-9a1c-e65d084c015b)
It's my graph-genome，can you answer me what to index path correctly ?
[yeast-pg.gfa.gz](https://github.com/codeatcg/VRPG/files/11494236/yeast-pg.gfa.gz)

**Comment by codeatcg** [comment]
Thanks. The discussion helps us to improve the program.  gfa2view didn't deal with the graph with non-consecutive segment ids correctly. But the ids in graph that published by Human Pangenome Reference Consortium (https://humanpangenome.org/) are consecutive. At least for graphs created by previous version of PGGB and Minigraph the ids are consecutive. We'll test more. The code has been modified to deal with the graph correctly. More modification about masking small variants (SNPs and INDELS) for views at a large scale are being tested.  We plan to synchronize these modifications to github within this week.

**Comment by zskey-zn** [comment]
Thanks , this problem has been solved.
